# Where the main .tex file is stored
texfile := "./libro.tex"

# The command that we want to use to rm files
# For example, "rm"
trash := "trash"

# Shows all recepies available in this justfile
default:
	just --list

# Compiles the latex document
compile:
	pdflatex "{{texfile}}"

# Compiles the project from zero
clean_compile:
    # Remove all artifacts, including final PDF
    just clean
    {{trash}} {{trim_end_match(texfile, ".tex")}}.pdf

    # Now compile
    just compile

# Cleans all the artifacts created during compilation
clean:
    {{trash}} *.log || echo "All .log files already removed"
    {{trash}} *.aux || echo "All .aux files already removed"
    {{trash}} *.toc || echo "All .toc files already removed"
    {{trash}} *.out || echo "All .out files already removed"
