# Github action for installing dependencies using poetry, and running unit tests

name: Install dependencies and run integration tests using enviroment declared in poetry

# Only run integration tests on pull request
# On push might be too much
on:
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  integration_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry package manager
      run: pip install poetry
    - name: Install dependencies using poetry
      run: |
        poetry install
    - name: Run integration tests with unitttest module
      run: |
        poetry run python -m unittest src/integration_tests/*.py
