# Github action for installing depende0cies using conda dump, and running unit tests
# Conda dump is in `enviroment.yml` file

name: Install dependencies and run integration tests using conda enviroment dump

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  integration_tests_conda:

    runs-on: ubuntu-latest

    # Conda needs a loggin shell to be able to run `conda activate`
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3

    # Activate the conda enviroment using the dump of the enviroment
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: /mnt/homeGPU/squijano/TFG/custom_env_squijano
        environment-file: environment.yml
        auto-activate-base: false

    - name: Run integration tests with unitttest module
      run: |

        # For debuggin purposes
        conda list

        # Run the integration test using the conda enviroment
        conda run python -m unittest src/integration_tests/*.py
