# Github action for installing depende0cies using conda dump, and running unit tests
# Conda dump is in `enviroment.yml` file

name: Install dependencies and run integration tests using conda enviroment dump

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  integration_tests_conda:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.17"

    - name: Install dependencies using conda
      run: |
        # $CONDA points to the path of the dir where conda is installed
        $CONDA/bin/conda env update --file enviroment.yml --name /mnt/homeGPU/squijano/TFG/custom_env_squijano

    - name: Run integration tests with unitttest module
      run: |

        # Run the integration test using the conda enviroment
        $CONDA/bin/python -m unittest src/integration_tests/*.py
