# Github action for installing depende0cies using conda dump, and running
# some notebooks so we are sure that they still run even though we make changes
# in the `.py` code
name: Install dependencies and run some notebooks

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  integration_tests:

    runs-on: ubuntu-latest

    # Conda needs a loggin shell to be able to run `conda activate`
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3

    # Activate the conda enviroment using the dump of the enviroment
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: squijano
        environment-file: enviroment.yml
        auto-activate-base: false

    - name: Run certain notebooks
      run: |
        jupyter nbconvert --execute "src/FG-Net Notebook.ipynb" --to "html"
